// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SL.InfraSL;

namespace SL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230310033556_altertables")]
    partial class altertables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SL.Domain.Models.PermisoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permiso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("permiso");
                });

            modelBuilder.Entity("SL.Domain.Models.Permiso_PermisoModel", b =>
                {
                    b.Property<int>("id_permiso_permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("id_permiso_hijo")
                        .HasColumnType("int");

                    b.Property<int?>("id_permiso_padre")
                        .HasColumnType("int");

                    b.HasKey("id_permiso_permiso");

                    b.ToTable("permiso_permiso");
                });

            modelBuilder.Entity("SL.Domain.Models.UsuarioModel", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dni")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("idioma")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pw")
                        .IsRequired()
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_usuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("SL.Domain.Models.Usuario_PermisoModel", b =>
                {
                    b.Property<int?>("id_permiso")
                        .HasColumnType("int");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("int");

                    b.HasKey("id_permiso", "id_usuario");

                    b.HasIndex("id_usuario");

                    b.ToTable("usuarios_permisos");
                });

            modelBuilder.Entity("SL.Domain.Models.Usuario_PermisoModel", b =>
                {
                    b.HasOne("SL.Domain.Models.PermisoModel", "PermisoModel")
                        .WithMany("Usuario_Permisos")
                        .HasForeignKey("id_permiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SL.Domain.Models.UsuarioModel", "UsuarioModel")
                        .WithMany("Usuario_Permisos")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermisoModel");

                    b.Navigation("UsuarioModel");
                });

            modelBuilder.Entity("SL.Domain.Models.PermisoModel", b =>
                {
                    b.Navigation("Usuario_Permisos");
                });

            modelBuilder.Entity("SL.Domain.Models.UsuarioModel", b =>
                {
                    b.Navigation("Usuario_Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
