// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Models;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public class ClienteModel
    {
        public ClienteModel()
        {
            this.Pedido = new HashSet<PedidoModel>();
        }

        public int Id_Cliente { get; set; }
        public string Teléfono { get; set; }
        public string Nombre { get; set; }
        public string Dirección { get; set; }
        public string MailContacto { get; set; }
        public string DNI { get; set; }
        public bool? Active { get; set; }

        [NotMapped]
        public virtual ICollection<PedidoModel> Pedido { get; set; }
    }
}