// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Models;

using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public class DetalleModel
    {
        public int Id_Pedido { get; set; }
        public Guid Id_Producto { get; set; }
        public int Cantidad { get; set; }
        public int Id_Detalle { get; set; }
        public string Tipo { get; set; }


        public virtual PedidoModel Pedido { get; set; }
        public virtual ProductoModel Producto { get; set; }
    }
}