// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public class PedidoModel
    {
        public PedidoModel()
        {
            this.DetallePedido = new HashSet<DetalleModel>();
            this.Factura = new HashSet<FacturaModel>();
        }

        public int Id_Pedido { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public string Descripción { get; set; }
        public string? Dirección { get; set; }
        public string Estado { get; set; }
        public DateTime FechaHora { get; set; }
        public decimal Total { get; set; }
        public string? TelefonoContacto { get; set; }
        public string? Retiro { get; set; }

        [NotMapped]
        public virtual ClienteModel Cliente { get; set; }
        public virtual ICollection<DetalleModel> DetallePedido { get; set; }
        public virtual ICollection<FacturaModel> Factura { get; set; }
    }
}